FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY train.py retrain_api.py ./
COPY Data ./Data
COPY Model ./Model

CMD ["uvicorn", "retrain_api:app", "--host", "0.0.0.0", "--port", "8001"]
