version: '3.8'

services:
  personality-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personality-app
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount local directories for development
      - ./Model:/app/Model:ro
      - ./Data:/app/Data:ro
      - ./Results:/app/Results
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - personality-net

networks:
  personality-net:
    driver: bridge

# Optional: Add volumes for persistent data
# volumes:
#   model-data:
#   results-data:
