name: Continuous Deployment (Alternative)

on:
  push:
    branches: ["Firman"]
  workflow_dispatch:

permissions: 
  contents: write
  actions: read

jobs:
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    # Tunggu 2 menit untuk memastikan CI selesai, lalu cek statusnya
    
    steps:
      - name: Wait for CI
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Continuous Integration'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Required Secrets
        run: |
          echo "Checking required secrets..."
          if [ -z "${{ secrets.HF_TOKEN }}" ]; then
            echo "❌ HF_TOKEN secret is not set!"
            exit 1
          fi
          echo "✅ All required secrets are configured"

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          echo "Starting deployment..."
          make deploy HF_TOKEN="$HF_TOKEN" USER_NAME="$USER_NAME" USER_EMAIL="$USER_EMAIL"
