name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches: ["Firman"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test CD
        run: echo "CD is working!"
        
      - uses: actions/checkout@v3

      - name: Deployment To Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          echo "Starting deployment with HF token..."
          echo "Token exists: $(if [ -n "$HF_TOKEN" ]; then echo "YES"; else echo "NO"; fi)"
          echo "User: $USER_NAME <$USER_EMAIL>"
          make deploy HF_TOKEN="$HF_TOKEN" USER_NAME="$USER_NAME" USER_EMAIL="$USER_EMAIL"
