name: Continuous Integration

on:
  push:
    branches: ["Firman"]
  pull_request:
    branches: ["Firman"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Packages
        run: make install

      - name: Format Code
        run: make format

      - name: Train Model
        run: make train

      - name: Setup Node.js (for CML)
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install CML
        run: npm install -g @dvcorg/cml

      - name: Evaluate Model
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      - name: Update Branch
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$USER_NAME USER_EMAIL=$USER_EMAIL
