name: CI

on:
  push:
    branches: ["Firman"]
  pull_request:
    branches: ["Firman"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: make install
      - name: format
        run: make format
      - name: train
        run: make train
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install-cml
        run: npm install -g @dvcorg/cml
      - name: eval
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
      - name: update-branch
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$USER_NAME USER_EMAIL=$USER_EMAIL
